<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\PhoneCam.Core\PhoneCam.Core.csproj" />

        <PackageReference Include="FFmpeg.AutoGen" Version="8.0.0" />
        <PackageReference Include="FFmpeg.Loader" Version="3.0.2" />
        <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
    </ItemGroup>

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <UseWindowsForms>true</UseWindowsForms>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>13.0</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

</Project>